### ISSUE TITLE
Native client link not working

### ISSUE THREAD

**Issue by davotoula** [fiatjaf/njump#13]
https://github.com/fiatjaf/njump/blame/9ce8d7970a036a285b13c34e7b3b341e33e71a5d/utils.go#L129

**Comment by fiatjaf** [comment]
How is it not working exactly? It works for me on Android. I click and it prompts me to select an installed Nostr client to open the event in.

**Comment by davotoula** [comment]
I get this url on android and on desktop

https://njump.me/nevent1qqstpwqn5yfr9re2kzg4uxqkrjt59yz4csptn5v87m225m4tlduaz4syg2ngt#ZgotmplZ

I've looked at the code but not sure where the "code" ZgotmplZ is generated.

**Comment by davotoula** [comment]
I get this url on android and on desktop

https://njump.me/nevent1qqstpwqn5yfr9re2kzg4uxqkrjt59yz4csptn5v87m225m4tlduaz4syg2ngt#ZgotmplZ

I've looked at the code but not sure where the "code" ZgotmplZ is generated.

I'm using Brave browser on android and Desktop.

**Comment by fiatjaf** [comment]
Oh, I see it now.
