### ISSUE TITLE
Add nostr logo to njump

### ISSUE THREAD

**Issue by alltheseas** [fiatjaf/njump#15]
_suggestion_

Add nostr logo to the njump to build nostr brand, and improve association and recognizability of njump & nostr. 

_mockup_

![image](https://github.com/fiatjaf/njump/assets/64376233/501a06dd-522b-4c93-a486-b3361b4f459e)

logo via https://github.com/Creative-Network-Live/FOSD-Nostr/tree/main/Icon/400x400

**Comment by fiatjaf** [comment]
I agree, but first we must get rid of the ostriches.

**Comment by alltheseas** [comment]
How is this 

![plaintext nostr logo](https://github.com/fiatjaf/njump/assets/64376233/f4ad4581-7a03-4be1-b512-0e202eea92e1)

**Comment by fiatjaf** [comment]
That is better.

**Comment by alltheseas** [comment]
Ok. Here is the collateral. I think this is better than the current njump, and I'm sure designers can come up with something better when they have interest to iterate. 

Font: Istok web

SVG:
![nostr logo](https://github.com/fiatjaf/njump/assets/64376233/4460a952-b6ea-4827-9992-3c56f90d364d)

https://www.figma.com/file/yAuJh46zIZ1RQelcIiloCv/Untitled?type=design&node-id=25%3A21&mode=design&t=8xL5iAXfy53uVoAK-1

**Comment by alltheseas** [comment]
@karnagebitcoin what do you think

**Comment by alltheseas** [comment]
Niel "N" suggestion

https://damus.io/note1q0d3a0z9x3pxsa6pa2fcwhgvlk26lhpm3fergw0amk9nmpm06rzqcr4zhj

**Comment by fiatjaf** [comment]
You didn't even use a njump link.

**Comment by karnagebitcoin** [comment]
Umm... 

It seems we have zero consensus on what a Nostr logo should be. I see different websites using different logos, and people proposing all sorts of stuff. 

Maybe this is ok. So, to @fiatjaf 's point, perhaps we should just include some text.  

Generally speaking I don't think Nostr should even work too hard at building a brand. I think this is a job for clients to be their own brands. That doesn't mean Nostr can't have a brand, but IMO we'd be better off if it didn't compete with client brands. 

I am also not sold on njump (at least not in its current state). I am willing to bet 99% of people who come to njump for the very first time (who are not familiar with nostr), have no idea what it is and probably think it's nostr itself. njump could very well be the first and last impression for anyone looking at nostr. Naturally, I think it has to be the best possible impression we can make. 

just my 2 sats

**Comment by karnagebitcoin** [comment]
To my last point, I think it may even be fine for clients to link to their own pages, as long as they have a page to link to. I don't think we need to offer options for people to open up with a client... I mean the word client itself is probably confusing to people. Like... wth are you talking about?! haha. 

What's wrong with linking to a snort note if a snort note is available to link to? IMO clients should build their own brand and do their own marketing and stop calling everything a NOSTR client. Just call Snort Snort and Damus Damus and let them build their own presence and voice. 

In the mobile case where clients have no linkable pages, njump is ok and should probably be designed to be as generic and plain as possible (see Threads desktop version minus the logo).

**Comment by karnagebitcoin** [comment]
![Uploading CleanShot 2023-11-10 at 09.57.04@2x.png…]()
Nice and plain.

**Comment by fiatjaf** [comment]
> What's wrong with linking to a snort note if a snort note is available to link to? IMO clients should build their own brand and do their own marketing and stop calling everything a NOSTR client. Just call Snort Snort and Damus Damus and let them build their own presence and voice.

There is no point in having a Nostr protocol then.

**Comment by karnagebitcoin** [comment]
Impersonate? Your words not mine. You had to have known the free markets that bitcoiners love so much will eventually force people to choose the best clients. There WILL be winners and losers, that's the nature of things. There will be clients with strong brands, good funding and marketing. Primal is going down that path. Damus has a strong brand already. 

I think clients that don't have indexed, linkable pages should absolutely use njump, but you can't really force other clients to do as you please. Isn't that the point of nostr - people can build whatever they want? Are you going to manually ask everyone nice to use njump? 

My main concern is and always will be the end user. If they don't understand what they are looking at, I have failed. I will always advocate for simplicity and ease of use, while giving people the optionality to do as they please. Sometimes that means opting in, sometimes opting out. If at the end of the day you have people absolute optionality to do as they please, with a million options all displayed up front, and nobody uses any of it (cumulatively speaking), then what is the point? We will have appealed to all the bitcoiners and all the techies and left everyone else behind. That is not inclusive. 

It'll always be a balance between convenience, ease of use and choices. The two experiences are valid for various types of users and perhaps we just need multiple services - one that seeks to help newbies and one that works for all nostr users who don't need their stuff tucked away. 

But, to my point, nobody can stop me just linking to a snort page right now, and that will never change for anyone unless all developers work together to make sure that is never the case - which to me seems like just shooting yourself in the foot - decisions by committee (and we all know how that works out usually).

**Comment by karnagebitcoin** [comment]
Let's just make 2 of everything 🤣

1. One for newbies with no technical details
2. One for everyone else, with all the technical details

As easy as forking and making some tweaks.

Let clients decide what they want to do.

Joking, but also not joking. I dunno...

**Comment by dtonon** [comment]
We shipped this:

<img width="597" alt="image" src="https://github.com/fiatjaf/njump/assets/89577423/47a387da-2494-4de2-a65e-2dc3ccfc8c11">
<br/><br/>
Maybe we will tweak the badge later.
