### ISSUE TITLE
Replace font: NotoSansTC.ttf to NotoSansSC.ttf

### ISSUE THREAD

**Issue by cxplay** [fiatjaf/njump#17]
NotoSansSC supports all Simplified and Traditional Chinese characters, but NotoSansTC does not support some Simplified Chinese characters. However, NotoSansSC's static file size has increased by 50% compared to NotoSansTC(10MB vs 6.8MB).

See in:
- [Noto Sans Simplified Chinese - Google Fonts](https://fonts.google.com/noto/specimen/Noto+Sans+SC/tester)
- [Noto Sans Traditional Chinese - Google Fonts](https://fonts.google.com/noto/specimen/Noto+Sans+TC/tester)
![image](https://github.com/fiatjaf/njump/assets/62034099/e63683d7-4cec-4735-80c7-326f554097fe)
![image](https://github.com/fiatjaf/njump/assets/62034099/e6311b65-31ae-43bb-867e-816beac78ff6)

If the increase in size of these static files is acceptable, then support for card rendering in Chinese would be further enhanced.

**Comment by cxplay** [comment]
Of course NotoSansSC also includes support for Japanese characters:

![image](https://github.com/fiatjaf/njump/assets/62034099/16444aea-9596-4955-a0b5-edcd21d0b747)
![image](https://github.com/fiatjaf/njump/assets/62034099/43771357-c058-49b1-8b07-ee5909f853fc)

However, it is not recommended as a replacement for NotoSansJP, as Chinese and Japanese handle punctuation very differently.

**Comment by fiatjaf** [comment]
Let me know if this works.

**Comment by cxplay** [comment]
> Let me know if this works.

I tested it locally, no problem at all, thanks!
