### ISSUE TITLE
go generate does not work

### ISSUE THREAD

**Issue by mattn** [fiatjaf/njump#29]
As far as I treid to build, tmpl does not handle go files.

Do you use https://github.com/tylermmorton/tmpl/cmd/tmpl ?

**Comment by fiatjaf** [comment]
No, we were using using that but changed now to https://templ.guide/.

Looking at the [justfile](../blob/master/justfile) should give you a better idea, but the build process requires building the tailwind thing, then the templ thing, and finally the binary.
