### ISSUE TITLE
line-height: 0px; breaks everything

### ISSUE THREAD

**Issue by vitorpamplona** [fiatjaf/njump#43]
this line: 

https://github.com/fiatjaf/njump/blame/c51ed56d1408d5456170ee7c5bf404f945af1988/common.templ#L27

results in this: 

![Screenshot 2024-02-13 at 10 54 26 AM](https://github.com/fiatjaf/njump/assets/532031/6f4d64c3-96e3-4e08-a67f-0748e36ffaba)

**Comment by vitorpamplona** [comment]
@mattn

**Comment by mattn** [comment]
@vitorpamplona Could you please give the event ID please.

**Comment by vitorpamplona** [comment]
All multi-line events are broken. 

https://njump.me/nevent1qythwumn8ghj7un9d3shjtnwdaehgu3wvfskuep0qy88wumn8ghj7mn0wvhxcmmv9uq3vamnwvaz7tmjv4kxz7fwd4hhxarj9ec82c30qythwumn8ghj7mn0wd68ytnwdahkuetn9e3k7mf0qydhwumn8ghj7mn0wd68ytn0wfskuem9wp5kcmpwv3jhvtcpzemhxue69uhk2er9dchxummnw3ezumrpdejz7qg3waehxw309ahx7um5wgh8w6twv5hszythwden5te0xy6rqtnxxaazu6t09uq32amnwvaz7tmjv4kxz7fwv3sk6atn9e5k7tcpzdmhxue69uhhqatjwpkx2urpvuhx2ue0qqsxxkrs3g0jeekurew3087ujwkyns5hcdlmu5l92zv0hd9g9alvnhsvk3ljm

**Comment by mattn** [comment]
Thank you. Address in https://github.com/fiatjaf/njump/pull/45
