### ISSUE TITLE
Some Random Content not working. 

### ISSUE THREAD

**Issue by seanmurphy1661** [fiatjaf/njump#50]
_some random content_ link is not working due to malformed href on the index page. 

View page source reveals:

`<a class="underline" href="[/random](view-source:https://njump.me/random)" _="on click halt the event then fetch /random with method:&#39;POST&#39; then tell &lt;input[name=&#39;code&#39;] /&gt; set @value to result">some random content</a>`

obvi not a big deal, but i rarely find bugs...

**Comment by dtonon** [comment]
For me it works fine.
When you click on the link, doesn't a new entity appear in the input?
If not, tell me the browser+version you are using, please.

The code seems malformed, but actually it is a correct Hyperscipt syntax/encoding.

<img width="583" alt="Screenshot 2024-02-25 alle 23 15 18" src="https://github.com/fiatjaf/njump/assets/89577423/3eaa5a3f-5bd5-47d4-92c7-c2b6ea1931f0">

**Comment by seanmurphy1661** [comment]
Nothing happens. Open in new tab works. 

![image](https://github.com/fiatjaf/njump/assets/4969079/df17bb1e-49db-4e29-b2f7-b67e615a3683)

**Comment by seanmurphy1661** [comment]
ok, yes, something does appear in the box. i get it now. i was expecting the link to also nav to the event.
