### ISSUE TITLE
How to get service with domain name?

### ISSUE THREAD

**Issue by mattn** [fiatjaf/njump#75]
https://njump.me/fiatjaf.com service your profile. But https://njump.me/compile-error.net does not service my profile. What is wrong?

**Comment by fiatjaf** [comment]
The `"relays"` object in https://compile-error.net/.well-known/nostr.json is wrong, it must be a map of arrays, not just an array. See https://fiatjaf.com/.well-known/nostr.json.

**Comment by mattn** [comment]
Thanks.
