### ISSUE TITLE
Njump encodes naddrs in hyperlinks incorrectly

### ISSUE THREAD

**Issue by SilberWitch** [fiatjaf/njump#81]
In this [30040 event](https://njump.me/nevent1qqs8hp0e6ahazxjwc6xy6hhsfwc3ayk7umnul3mc8rjygxv90y97wcspzemhxue69uhhyetvv9ujumn0wd68ytnzv9hxgq3q2umrfdjgvdxt45g0y3ghwcyfagssjrv5qlm3t6pu2aa5vydwdmwqshnnfd), some of the a-tag hyperlinks take you to the correct naddr (`d` tags containing _with-a-tags_), and some take you to the wrong naddr  (`d` tags containing _with-e-tags_).

For example, the first one is correct, the second link is incorrect.

You can see the eventID that it should end up at, at the end of the a tag, according to the [NIP-62 convention](https://github.com/nostr-protocol/nips/pull/1600/files).

**Comment by fiatjaf** [comment]
I don't get it. If you want to link to a specific event id why not use an `e` tag?

**Comment by SilberWitch** [comment]
We want to use it for versioning.

**Comment by SilberWitch** [comment]
For clarification, the naddr in the njump hyperlink is correct, but njump is displaying something with a slightly different naddr. The URL and the page content don't pricisely match. The `d` tags differ by one character.

For comparison, with the same naddr, rendered in [Njump](https://njump.me/naddr1qppxzetndac8xttxv93xcetn946xsefddahx2tt909jkgttydajj6dedvfuj6um0wqkhvtt5v4ehgttkv4e8x6t0dckhw6t5dqkkztt5v9nhxqgmwaehxw309a6xsetrd96xzer9dshxummnw3erztnrdaksygzhxc6tvjrrfjadzrey29mkpz02yyysm9q87u27s0zh0drprtnwmspsgqqqw4vsjyluky) versus in [Nostrudel](https://nostrudel.ninja/#/l/naddr1qppxzetndac8xttxv93xcetn946xsefddahx2tt909jkgttydajj6dedvfuj6um0wqkhvtt5v4ehgttkv4e8x6t0dckhw6t5dqkkztt5v9nhxqgmwaehxw309a6xsetrd96xzer9dshxummnw3erztnrdaksygzhxc6tvjrrfjadzrey29mkpz02yyysm9q87u27s0zh0drprtnwmspsgqqqw4vsjyluky) (or Nak.nostr.com).

**Comment by fiatjaf** [comment]
I checked and everything looks correct to me, njump is ignoring the event id you have there, it's just making the `naddr` link based on the first value of the `a` tag.

The njump and Nostrudel links also seem to be rendering the same event. And on Nostrudel you can get a link to njump that displays exactly the same event.

What am I missing?

**Comment by SilberWitch** [comment]
It's kind of hard to see because I have the event in two versions, and only one character is different. The correct one says "with **a** tags" in the d-tag and the incorrect one says "with **e** tags".

![image](https://github.com/user-attachments/assets/32364676-fd76-4481-a1a8-052c4cc1d0a1)

**Comment by SilberWitch** [comment]
The events are otherwise the same because it's the 30040 event that lists them, that differs between a/e.

The `d` tag is sort of long, so I was thinking that it might be cutting off the end bit, and ending up with identical-looking d-tags.

**Comment by SilberWitch** [comment]
If you go to Nostrudel and look at the code, the event has an ID of 6dde51540e8173532099e5f7730b51d8083d87984417bd6bcea307f9dcd415c7 and a note1dh09z4qws9e4xgyeuhmhxz63mqyrmpucgstm667w5vrlnhx5zhrsljsplw , both of which take me to the correct nevent on Njump https://njump.me/nevent1qqsxmhj32s8gzu6nyzv7tamnpdgaszpas7vyg9aad082xplemn2pt3cpzemhxue69uhhyetvv9ujumn0wd68ytnzv9hxgq3q2umrfdjgvdxt45g0y3ghwcyfagssjrv5qlm3t6pu2aa5vydwdmwq4mldpp 

But the naddr links to the wrong event on njump. Here is the naddr, decoded in NAK, where it also shows the correct information.
![image](https://github.com/user-attachments/assets/aa9f6b3a-4fec-463a-b2b1-219f963a32a6)

The problem is between the njump URL and the rendering in the njump client. The naddr itself, is correct.

**Comment by fiatjaf** [comment]
![2024-12-18-131441_693x879_scrot](https://github.com/user-attachments/assets/364e9875-efe6-4442-a24c-afdb78e30b18)

I still don't get it.

All links are to `-with-a-tags-` in the event you linked, and they all lead to the correct events:

![2024-12-18-131623_661x449_scrot](https://github.com/user-attachments/assets/b1424048-5bb3-4074-a715-aaf88983f1c5)

**Comment by SilberWitch** [comment]
1-3 work for me, 4-7 don't. Could it be a caching issue? The first couple tries I had with my CLI, the  d-tags were wrong and contained an e.

Just asking, because this morning, 1 worked and the rest didn't. Now 1-3 work and the rest don't.

**Comment by fiatjaf** [comment]
All seem to work for me (unless I'm misreading). I don't see how this could be a caching issue because the `d` tag being different would invalidate everything, but maybe. If I could reproduce it would be better to test.

**Comment by SilberWitch** [comment]
Yeah. Weird bug. Now, 1-3 and 7 work for me. 😂

Well, whatever. At least, we can see that Njump can handle the new a tags.
